baseURL = "https://onepaperhoon.github.io/"
languageCode = "en-us"
title = "OnePaperHoon Dev Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  showReadingTime = false
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  mainSections = ["content"]

[menu]
  [[menu.main]]
    name = "Home"
    url = ""
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 2
  [[menu.main]]
    name = "OpenGL"
    url = "opengl/"
    weight = 3

