baseURL = "https://onepaperhoon.github.io/"
languageCode = "en-us"
title = "OnePaperHoon Dev Blog"
theme = "PaperMod"

[params]
  showReadingTime = true
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  mainSections = ["posts"]
  disableKinds = ["taxonomy", "term"]
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

